### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LXWDL** [ReProduceByYQ/Channel_pruning_yq#1]
Hi,thanks for sharing, but I get the following error when I run your code:
Traceback (most recent call last):
  File "./low_rank_and_channel_pruning.py", line 12, in <module>
    from util import *    # my function
ImportError: No module named 'util'
Can you share this file you wrote?thanks

**Comment by Johnson-yue** [comment]
@LXWDL hi, it is my fault, I have uploaded **util.py** file,  you can try again!!
