### ISSUE TITLE
how to set the config.json

### ISSUE THREAD

**Issue by young-fire** [ReProduceByYQ/Channel_pruning_yq#3]
thanks for your sharing, is simpler to understand than oringal code. then,the question is as follows:
{
  "conv1_2": 24,
  "conv2_1": 48,
  "conv2_2": 48,
  "conv3_1": 64,
  "conv3_2": 128,
  "conv3_3": 160,
  "conv4_1": 192,
  "conv4_2": 192,
  "conv4_3": 256,
  "conv5_1": 320,
  "conv5_2": 320,
  "conv5_3": 320
}

How to calculate and get this number?

**Comment by Johnson-yue** [comment]
It is not calculate number, it is a experimental number!  you can set any other number to test .So it is not certainly
