### ISSUE TITLE
about Lasso regression

### ISSUE THREAD

**Issue by young-fire** [ReProduceByYQ/Channel_pruning_yq#4]
When I test it ,after lasso regression ,I do this:                    
 count = sum(idxs)
 idxs[0:count]=True
idxs[count:]=False
the number of filters is the same , but  the first count filters to preserve. the top5 and top1 is no descend ,why?

**Comment by young-fire** [comment]
pls  test it ,maybe some wrong in my code.

**Comment by Johnson-yue** [comment]
sorry， I can not understand what would you do ? After Lasso regression, the mask of channel in the __idxs__ ,
`count = sum(idxs)`
the __count__ should be equal to rank!  and it is not successive，so， why you do 
`idxs[0:count]=True
idxs[count:]=False  
`
This two line code have modified result of Lasso  . It is mistake!!
Can you tell me what do you want to do ?

**Comment by young-fire** [comment]
yes,This two line code have modified result of Lasso,Use this result to reshape the W, then the top5 is no decline.

**Comment by young-fire** [comment]
I mean  use this mistake result get  the same accuracy.

**Comment by young-fire** [comment]
oh , i konw ,i use the method named fisrt k  , in single-layer it is almost no loss .
